get-focus/focus-graph

- src/behaviours/definitions.js
- src/behaviours/field.js
- src/behaviours/smart-data.js
- src/components/dumb.js
- src/index.js
- src/reducers/entity-reducer.js
- Works with functional component
- Fix behaviours
- Use compose
- Remove smart component
> State bridge

- .travis.yml
- package.json
- src/actions/__tests__/entity-action-builder-test.js
- src/actions/entity-actions-builder.js
- test/mocha-bootload.js
- test/mocha.opts
-  [x] Add mocha, sinon, react addons dependencies
-  [x] Add travis ci
- write tests for action builder
> [test] Setup and action builder tests

- src/actions/__tests__/entity-action-builder-test.js
- src/actions/entity-actions-builder.js
- src/example/actions/user-actions.js
> Feature multiple entities

- .flowconfig
- package.json
- src/behaviours/documentation.js
- src/components/panel.js
- src/example/components/card.js
- src/example/components/display-only.js
- src/example/components/home.js
- src/example/components/menu.js
- src/example/components/multi-block-page/index.js
- src/example/components/multi-block-page/user-address-informations.js
- src/example/components/no-match.js
- src/example/components/param-extractor.js
- src/example/config.js
- src/example/containers/dev-tools.js
- src/example/index.js
> [WIP] Feature examples

- package.json
- src/actions/form.js
- src/behaviours/__tests__/form-test.js
- src/example/store/index.js
- src/reducers/form.js
- src/store/builder.js
- src/store/selectData.js
- `CLEAN_FIELDS` remove a field and set `null` in its value
> Action clean fields

- src/components/display.js
- src/components/field.js
- src/example/config.js
- the props are now passed to the display component
> OtherProps to display

- package.json
- src/components/field.js
- src/reducers/form.js
Linked to https://github.com/get-focus/focus-redux/issues/39 compatibility with focus components
> Fix compat focus component value

- src/components/list.js
https://github.com/get-focus/focus-graph/issues/56
> OnClick on the line

- src/actions/entity-actions-builder.js
- src/example/actions/user-actions.js
- src/example/components/custom-user-form.js
- src/example/components/user-form.js
> Feature action builder

- src/behaviours/field.js
Allow user to set `{options}` to the `fieldFor`
> [fieldFor] Add options.

- src/reducers/reducer-builder.js
> Fix reducerBuilder requires a saveTyoes attribute

- src/behaviours/field.js
- src/example/components/user-form.js
- src/example/reducers/user-reducer.js
- src/middlewares/field.js
Now, it's not possible to have something else other than an array in the default_data. 
#53 
There no error when there is no entityPathArray with the fieldBehaviour 
#83
> Fix default_data in the listFor

- src/behaviours/field.js
- src/components/line.js
- src/components/list.js
- src/components/select.js
- src/example/components/custom-user-form.js
- src/example/components/user-form.js
- src/example/config.js
- src/example/reducers/user-reducer.js
- src/middlewares/field.js
#79 
#61 
SelectForLine and TextForLine
> Fix select for line

- src/components/line.js
- src/components/select.js
- src/example/components/user-form.js
- src/example/config.js
It's possible to use the selectFor with the props values .
> fix using select with no reference list

- package.json
- src/actions/form.js
- src/behaviours/field.js
- src/behaviours/form.js
- src/components/field.js
- src/example/components/user-form.js
- src/example/index.js
- src/example/store/index.js
- src/reducers/form.js
- src/store/create-store.js
It's possible to give an InputComponent and a DisplayComponent to the FieldHelperProvider
> Feature input component

- package.json
- src/actions/form.js
- src/example/components/user-form.js
- src/reducers/__tests__/form-reducer-test.js
- src/reducers/form.js
Updating the clear action to give the possibility to restore default value
> [WIP] Updating clear

- .travis.yml
> Feature travis node 6

- package.json
- src/reducers/form.js
Adding a condition for the clear
> Fix reducer

- package.json
- src/actions/entity-actions-builder.js
- src/example/actions/mixed-actions.js
- src/example/components/user-form.js
- src/example/config.js
- src/middlewares/field.js
- src/middlewares/form.js
- src/middlewares/validations.js
> Load the fields in the dataset and the definitions

- package.json
- src/behaviours/field.js
- src/components/field.js
- src/components/label.js
- src/components/list.js
- src/components/smart-select.js
- src/middlewares/form.js
- src/reducers/__tests__/form-reducer-test.js
- src/reducers/form.js
- src/style/field.scss
> Fix raw input value components

- src/actions/__tests__/entity-action-builder-test.js
- src/actions/entity-actions-builder.js
- src/behaviours/__tests__/form-test.js
- src/behaviours/form.js
- src/example/components/custom-user-form.js
- src/example/config.js
- src/example/services/user-service.js
- src/middlewares/__tests__/form-middleware-test.js
- src/middlewares/field.js
- src/middlewares/form.js
- src/middlewares/validate.js
- src/middlewares/validations.js
- src/reducers/reducer-builder.js
> [FieldMiddlaxare] validation on the async action

- src/behaviours/field.js
- src/components/field.js
- src/components/select.js
> fix components behaviours

- src/middlewares/validate.js
- src/middlewares/validations.js
The checkbox type is now added on the validation. This PR also fixes the fact that previously, true/false values wasn't been taken in consideration. 
> Fixes #134 
> Fixes #135
> [Validation] Add checkbox validation

- src/behaviours/field.js
- src/components/list.js
- src/middlewares/__tests__/form-middleware-validation.js
- src/middlewares/validations.js
- src/reducers/form.js
> Fixing the empty string case

- package.json
- src/behaviours/field.js
- src/behaviours/form.js
- src/behaviours/master-data.js
- src/behaviours/metadata.js
- src/middlewares/validations.js
Adjusting performances thanks to @JabX
> [form] Updating getUserInput

- package.json
- src/behaviours/field.js
The pure component breaked material design
> [field-behaviour]Fixing the field behaviour

- src/middlewares/field.js
> fix field middleware action build on sync_form

- api/index.js
- package.json
- src/actions/__tests__/entity-action-builder-test.js
- src/actions/entity-actions-builder.js
- src/behaviours/form.js
- src/example/actions/user-actions.js
- src/example/components/user-error.js
- src/example/config.js
- src/example/services/user-service.js
- src/middlewares/__tests__/form-middleware-test.js
- src/middlewares/field.js
- src/middlewares/form.js
- src/reducers/form.js
- src/reducers/reducer-builder.js
> [FormMiddleware] Fix rawInputValue clear on error server

- src/components/select.js
- src/components/smart-select.js
Giving a to the select component to have a default value when it's given
> [SmartSelect/Select] Add default value
